declare type $HTMLElementProps = {
  className?: string,
  contentEditable?: string,
  draggable?: boolean,
  id?: string,
  onBlur?: ?(ev: Event) => void,
  onChange?: ?(ev: Event) => void,
  onClick?: ?(ev: Event) => void,
  onFocus?: ?(ev: Event) => void,
  onKeydown?: ?(ev: Event) => void,
  onKeypress?: ?(ev: Event) => void,
  onKeyup?: ?(ev: Event) => void,
  onMousedown?: ?(ev: Event) => void,
  onMouseenter?: ?(ev: Event) => void,
  onMouseleave?: ?(ev: Event) => void,
  onMousemove?: ?(ev: Event) => void,
  onMouseout?: ?(ev: Event) => void,
  onMouseover?: ?(ev: Event) => void,
  onMouseup?: ?(ev: Event) => void,
  style?: CSSStyleDeclaration,
  tabIndex?: number,
  children?: React$Node,
  // TODO: Add more generic props here
}
